version: '3.8'

services:
  mysql:
    image: mysql:8.0.41
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecom_user
      MYSQL_PASSWORD: ecom_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "ecom_user", "-pecom_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: ecom_user
      SPRING_DATASOURCE_PASSWORD: ecom_pass
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  product-service:
    build:
      context: ./product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: ecom_user
      SPRING_DATASOURCE_PASSWORD: ecom_pass
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  order-service:
    build:
      context: ./order-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: ecom_user
      SPRING_DATASOURCE_PASSWORD: ecom_pass
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: ecom_user
      SPRING_DATASOURCE_PASSWORD: ecom_pass
    depends_on:
      mysql:
        condition: service_healthy
      order-service:
        condition: service_started
    restart: on-failure

volumes:
  mysql_data: