version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-rds-instance.cotseakug62f.us-east-1.rds.amazonaws.com:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
    restart: on-failure

  product-service:
    build:
      context: ./product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-rds-instance.cotseakug62f.us-east-1.rds.amazonaws.com:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
    restart: on-failure

  order-service:
    build:
      context: ./order-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-rds-instance.cotseakug62f.us-east-1.rds.amazonaws.com:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
    restart: on-failure

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-rds-instance.cotseakug62f.us-east-1.rds.amazonaws.com:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
    restart: on-failure
